### ISSUE TITLE
Incorrect git use.

### ISSUE THREAD

**Issue by DanBuchan** [StreetCredSoftware/PKIC#1]
Hi,

I've notice in your db/ directory you've got what appears to a history of  be a uniquely named files PKIC_2015_v.0.98.00.csv, PKIC_2015_v.0.99.00.csv etc....

One of the main benefits of source control is avoiding having to uniquely and manually label files with this kind of numbering scheme.

Typically you would check in a file with a given name (say PKIC_2015.csv) and then whenever you update that files GIT saves the history of all the prior changes and updates such that the most current version of db/ would just appear to have one file in it but the full history of prior would available. Git then provides Git Tags if you need to mark specific points in the history as a valid and correct "release"

**Comment by nselby** [comment]
Thanks so much. I was trying to make it so that we would be transparent in the changes we made, so that there would never be a question of checking previous versions of the file.And now you point out that this was, in fact, me not understanding some basics of the product. I appreciate your comment. Thanks!!
Nick

**Comment by DanBuchan** [comment]
Hi,

I've cloned and corrected your repo at

https://github.com/DanBuchan/pkic_corrected

Note how the HEAD of the master branch just has the latest file in the DBs/ but the history of the repo preserves all the prior versions of the DB. I also added all the comments you'd used to the history and I  tagged (git tag SOME_TAG") each commit with the version numbers you'd used.

Now in the github Interface users can click on the 'commits' link and view the history of all prior file/db changes. If I click on the 'releases' I can see all the named tags. If I click on the drop down for the Branches I can also explore the named tags.

If you want you can clone my version and replace yours (you may have to delete your old repo on github, and start a fresh empty one to hold my corrections)

**Comment by nselby** [comment]
Thanks. I actually already unified everything and re-ordered/named. Can you
have a look there? thanks for all your help, which I appreciate very much!

nick

On Sun, Nov 22, 2015 at 3:58 PM, Daniel notifications@github.com wrote:

> Hi,
> 
> I've cloned and corrected your repo at
> 
> https://github.com/DanBuchan/pkic_corrected
> 
> Note how the HEAD of the master branch just has the latest file in the
> DBs/ but the history of the repo preserves all the prior versions of the
> DB. I also added all the comments you'd used to the history and I tagged
> (git tag SOME_TAG") each commit with the version numbers you'd used.
> 
> Now in the github Interface users can click on the 'commits' link and view
> the history of all prior file/db changes. If I click on the 'releases' I
> can see all the named tags. If I click on the drop down for the Branches I
> can also explore the named tags.
> 
> If you want you can clone my version and replace yours (you may have to
> delete your old repo on github, and start a fresh empty one to hold my
> corrections)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/StreetCredSoftware/PKIC/issues/1#issuecomment-158799140
> .

## 

## 

Nick Selby
StreetCred Software, Inchttp://streetcredsoftware.com

mob 817 203 4074
fax 817 659-2996

3901 Arlington Highlands Blvd, Ste. 200
Arlington, TX 76018

## 

_Watch a two-minute overview of StreetCred Warrants - what it is, how
it works, and how it helps police and courts reduce their arrest
warrant backlog: http://goo.gl/AOAuMc http://goo.gl/AOAuMc_

"With StreetCred, officers in the field get a mobile, visual
presentation of available data in a way that equips them to make smart
decisions, again and again." - Next City http://goo.gl/Ga4ceW

**Comment by DanBuchan** [comment]
To be honest at this point they are more or less equivalent. I guess my version slightly better preserves the tag and comment history but that's of very, very marginal utility especially if you're expecting to have hundreds of commits going forward. 

One thing I'd suggest for your latest repo, tag each commit with your version number.  Assuming you're using the commandline you'd do something like this after each commit:

git tag v.1.00.002
git push --tags

**Comment by nselby** [comment]
I get it. THANK YOU that is great. I really appreciate this. BTW are you
working with the data in any interesting way?

On Sun, Nov 22, 2015 at 4:09 PM, Daniel notifications@github.com wrote:

> To be honest at this point they are more or less equivalent. I guess my
> version slightly better preserves the tag and comment history but that's of
> very, very marginal utility especially if you're expecting to have hundreds
> of commits going forward.
> 
> One thing I'd suggest for your latest repo, tag each commit with your
> version number. Assuming you're using the commandline you'd do something
> like this after each commit:
> 
> git tag v.1.00.002
> git push --tags
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/StreetCredSoftware/PKIC/issues/1#issuecomment-158799963
> .

## 

## 

Nick Selby
StreetCred Software, Inchttp://streetcredsoftware.com

mob 817 203 4074
fax 817 659-2996

3901 Arlington Highlands Blvd, Ste. 200
Arlington, TX 76018

## 

_Watch a two-minute overview of StreetCred Warrants - what it is, how
it works, and how it helps police and courts reduce their arrest
warrant backlog: http://goo.gl/AOAuMc http://goo.gl/AOAuMc_

"With StreetCred, officers in the field get a mobile, visual
presentation of available data in a way that equips them to make smart
decisions, again and again." - Next City http://goo.gl/Ga4ceW

**Comment by DanBuchan** [comment]
Not using the data myself, was pointed at it by a friend more from curiosities sake. 

(btw, I'll close this issue as the repo is fixed)

**Comment by nselby** [comment]
Thanks for the help, which I appreciate very much

On Tue, Nov 24, 2015 at 10:18 AM, Daniel notifications@github.com wrote:

> Not using the data myself, was pointed at it by a friend more from
> curiosities sake.
> 
> (btw, I'll close this issue as the repo is fixed)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/StreetCredSoftware/PKIC/issues/1#issuecomment-159301180
> .

## 

## 

Nick Selby
StreetCred Software, Inchttp://streetcredsoftware.com

mob 817 203 4074
fax 817 659-2996

3901 Arlington Highlands Blvd, Ste. 200
Arlington, TX 76018

## 

_Watch a two-minute overview of StreetCred Warrants - what it is, how
it works, and how it helps police and courts reduce their arrest
warrant backlog: http://goo.gl/AOAuMc http://goo.gl/AOAuMc_

"With StreetCred, officers in the field get a mobile, visual
presentation of available data in a way that equips them to make smart
decisions, again and again." - Next City http://goo.gl/Ga4ceW
